package com.example.javanesescriptrecognizer;

import com.example.javanesescriptrecognizer.data.models.AksaraClasses.*;
import com.example.javanesescriptrecognizer.data.models.TypeEnums.*;

public class Constants {
    public static String[] JAVANESE_SCRIPT_CLASSES = new String[]{
            "01-aksara.wyanjana.ha",
            "02-aksara.wyanjana.na",
            "03-aksara.wyanjana.ca",
            "04-aksara.wyanjana.ra",
            "05-aksara.wyanjana.ka",
            "06-aksara.wyanjana.da",
            "07-aksara.wyanjana.ta",
            "08-aksara.wyanjana.sa",
            "09-aksara.wyanjana.wa",
            "10-aksara.wyanjana.la",
            "11-aksara.wyanjana.pa",
            "12-aksara.wyanjana.dha",
            "13-aksara.wyanjana.ja",
            "14-aksara.wyanjana.ya",
            "15-aksara.wyanjana.nya",
            "16-aksara.wyanjana.ma",
            "17-aksara.wyanjana.ga",
            "18-aksara.wyanjana.ba",
            "19-aksara.wyanjana.tha",
            "20-aksara.wyanjana.nga",
            "21-pasangan.wyanjana.ha",
            "22-pasangan.wyanjana.na",
            "23-pasangan.wyanjana.ca",
            "24-pasangan.wyanjana.ra",
            "25-pasangan.wyanjana.ka",
            "26-pasangan.wyanjana.da",
            "27-pasangan.wyanjana.ta",
            "28-pasangan.wyanjana.sa",
            "29-pasangan.wyanjana.wa",
            "30-pasangan.wyanjana.la",
            "31-pasangan.wyanjana.pa",
            "32-pasangan.wyanjana.dha",
            "33-pasangan.wyanjana.ja",
            "34-pasangan.wyanjana.ya",
            "35-pasangan.wyanjana.nya",
            "36-pasangan.wyanjana.ma",
            "37-pasangan.wyanjana.ga",
            "38-pasangan.wyanjana.ba",
            "39-pasangan.wyanjana.tha",
            "40-pasangan.wyanjana.nga",
            "41-aksara.murda.na",
            "42-aksara.murda.ka",
            "43-aksara.murda.ta",
            "44-aksara.murda.sa",
            "45-aksara.murda.pa",
            "46-aksara.murda.nya",
            "47-aksara.murda.ga",
            "48-aksara.murda.ba",
            "49-pasangan.murda.na",
            "50-pasangan.murda.ka",
            "51-pasangan.murda.ta",
            "52-pasangan.murda.sa",
            "53-pasangan.murda.pa",
            "54-pasangan.murda.nya",
            "55-pasangan.murda.ga",
            "56-pasangan.murda.ba",
            "57-aksara.rekan.kha",
            "58-aksara.rekan.gha",
            "59-aksara.rekan.dza",
            "60-aksara.rekan.fa",
            "61-aksara.rekan.za",
            "62-pasangan.rekan.kha",
            "63-pasangan.rekan.gha",
            "64-pasangan.rekan.dza",
            "65-pasangan.rekan.fa",
            "66-pasangan.rekan.za",
            "67-aksara.swara.a",
            "68-aksara.swara.i",
            "69-aksara.swara.u",
            "70-aksara.swara.e",
            "71-aksara.swara.o",
            "72-aksara.ganten.pa_cerek",
            "73-aksara.ganten.nga_lelet",
            "74-pasangan.ganten.pa_cerek",
            "75-sandhangan.wulu",
            "76-sandhangan.suku",
            "77-sandhangan.pepet",
            "78-sandhangan.taling",
            "79-sandhangan.tarung",
            "80-sandhangan.pangkon",
            "81-sandhangan.wigyan",
            "82-sandhangan.layar",
            "83-sandhangan.cecak",
            "84-sandhangan.cakra",
            "85-sandhangan.ceret",
            "86-sandhangan.pengkal",
    };

    public static JavaneseScript[] JAVANESE_SCRIPT_TYPES = new JavaneseScript[]{
            new WyanjanaAksara(WyanjanaType.ha),
            new WyanjanaAksara(WyanjanaType.na),
            new WyanjanaAksara(WyanjanaType.ca),
            new WyanjanaAksara(WyanjanaType.ra),
            new WyanjanaAksara(WyanjanaType.ka),
            new WyanjanaAksara(WyanjanaType.da),
            new WyanjanaAksara(WyanjanaType.ta),
            new WyanjanaAksara(WyanjanaType.sa),
            new WyanjanaAksara(WyanjanaType.wa),
            new WyanjanaAksara(WyanjanaType.la),
            new WyanjanaAksara(WyanjanaType.pa),
            new WyanjanaAksara(WyanjanaType.dha),
            new WyanjanaAksara(WyanjanaType.ja),
            new WyanjanaAksara(WyanjanaType.ya),
            new WyanjanaAksara(WyanjanaType.nya),
            new WyanjanaAksara(WyanjanaType.ma),
            new WyanjanaAksara(WyanjanaType.ga),
            new WyanjanaAksara(WyanjanaType.ba),
            new WyanjanaAksara(WyanjanaType.tha),
            new WyanjanaAksara(WyanjanaType.nga),
            new WyanjanaPasangan(WyanjanaType.ha),
            new WyanjanaPasangan(WyanjanaType.na),
            new WyanjanaPasangan(WyanjanaType.ca),
            new WyanjanaPasangan(WyanjanaType.ra),
            new WyanjanaPasangan(WyanjanaType.ka),
            new WyanjanaPasangan(WyanjanaType.da),
            new WyanjanaPasangan(WyanjanaType.ta),
            new WyanjanaPasangan(WyanjanaType.sa),
            new WyanjanaPasangan(WyanjanaType.wa),
            new WyanjanaPasangan(WyanjanaType.la),
            new WyanjanaPasangan(WyanjanaType.pa),
            new WyanjanaPasangan(WyanjanaType.dha),
            new WyanjanaPasangan(WyanjanaType.ja),
            new WyanjanaPasangan(WyanjanaType.ya),
            new WyanjanaPasangan(WyanjanaType.nya),
            new WyanjanaPasangan(WyanjanaType.ma),
            new WyanjanaPasangan(WyanjanaType.ga),
            new WyanjanaPasangan(WyanjanaType.ba),
            new WyanjanaPasangan(WyanjanaType.tha),
            new WyanjanaPasangan(WyanjanaType.nga),
            new MurdaAksara(MurdaType.na),
            new MurdaAksara(MurdaType.ka),
            new MurdaAksara(MurdaType.ta),
            new MurdaAksara(MurdaType.sa),
            new MurdaAksara(MurdaType.pa),
            new MurdaAksara(MurdaType.nya),
            new MurdaAksara(MurdaType.ga),
            new MurdaAksara(MurdaType.ba),
            new MurdaPasangan(MurdaType.na),
            new MurdaPasangan(MurdaType.ka),
            new MurdaPasangan(MurdaType.ta),
            new MurdaPasangan(MurdaType.sa),
            new MurdaPasangan(MurdaType.pa),
            new MurdaPasangan(MurdaType.nya),
            new MurdaPasangan(MurdaType.ga),
            new MurdaPasangan(MurdaType.ba),
            new RekanAksara(RekanType.kha),
            new RekanAksara(RekanType.gha),
            new RekanAksara(RekanType.dza),
            new RekanAksara(RekanType.fa),
            new RekanAksara(RekanType.za),
            new RekanPasangan(RekanType.kha),
            new RekanPasangan(RekanType.gha),
            new RekanPasangan(RekanType.dza),
            new RekanPasangan(RekanType.fa),
            new RekanPasangan(RekanType.za),
            new Swara(SwaraType.a),
            new Swara(SwaraType.i),
            new Swara(SwaraType.u),
            new Swara(SwaraType.e),
            new Swara(SwaraType.o),
            new Ganten(GantenType.paCerek),
            new Ganten(GantenType.ngaLelet),
            new Ganten(GantenType.pasanganPaCerek),
            new Sandhangan(SandhanganType.wulu),
            new Sandhangan(SandhanganType.suku),
            new Sandhangan(SandhanganType.pepet),
            new Sandhangan(SandhanganType.taling),
            new Sandhangan(SandhanganType.tarung),
            new Sandhangan(SandhanganType.pangkon),
            new Sandhangan(SandhanganType.wigyan),
            new Sandhangan(SandhanganType.layar),
            new Sandhangan(SandhanganType.cecak),
            new Sandhangan(SandhanganType.cakra),
            new Sandhangan(SandhanganType.ceret),
            new Sandhangan(SandhanganType.pengkal),
    };
}
